In [1]:
import os
import pandas as pd

In [2]:
#directories
working_directory = os.getcwd()
data_folder         = os.path.join(working_directory, "data"        )
intermediate_folder = os.path.join(working_directory, "intermediate")
results_folder      = os.path.join(working_directory, "results"     )

In [3]:
#import from CSV
dfWFRCSpeedsPM = pd.read_csv(os.path.join(data_folder, r"WFRC Speeds - PM.csv"))
dfWFRCSpeedsPM

,local_timestamp,network_id,source_id,length_mi,freeflow_mph,subsegment,vehicle_type,avg_speed_mph,stdev_speed_mph
0,2019-09-04 17:50:00,S191R2,-1003723873,0.037568,29.832031,False,all,25.340760,NaN
1,2019-09-04 17:50:00,S191R2,-1012376285,0.029950,21.381383,False,all,15.902132,NaN
2,2019-09-04 17:50:00,S191R2,-101959967,0.105608,16.957220,False,all,13.288644,NaN
3,2019-09-04 17:50:00,S191R2,-101965016,0.168131,32.677911,False,all,26.189553,NaN
4,2019-09-04 17:50:00,S191R2,-101965101,0.086942,26.837022,False,all,23.573580,NaN
...,...,...,...,...,...,...,...,...,...
13091416,2019-09-26 15:55:00,S191R2,1022149997,0.036853,34.203999,True,all,26.879275,NaN
13091417,2019-09-26 15:55:00,S191R2,122398619,0.093171,34.203999,True,all,26.879275,NaN
13091418,2019-09-26 15:55:00,S191R2,708269711,0.126332,34.203999,True,all,26.879275,NaN
13091419,2019-09-26 15:55:00,S191R2,708269710,0.121601,34.203999,True,all,26.879275,NaN
13091420,2019-09-26 15:55:00,S191R2,-1211979242,0.018950,34.203999,True,all,26.879275,NaN

In [5]:
dfWFRCSpeedsPM.groupby(['source_id']).agg(NUMREC=('source_id','size'))

             NUMREC
source_id
-1001077442     115
-1001965884     137
-1001965885     137
-1001965889     137
-1001965890     137
...             ...
999698161        37
999764042         9
999764043         9
999779193       343
999779194       343

[118109 rows x 1 columns]